# Generated by Django 5.0.3 on 2024-06-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messapp', '0002_message_attachment_messagegroup_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='avatar',
            field=models.ImageField(default='avatars/default_chat.jpg', upload_to='avatars/'),
        ),
    ]
