# Generated by Django 5.0.3 on 2024-06-07 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messapp', '0005_channel_messagechannel_messageview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='contributors',
        ),
    ]
