# Generated by Django 5.0.3 on 2024-06-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messapp', '0008_remove_channel_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='websocket_connected',
            field=models.BooleanField(default=False),
        ),
    ]
