# Generated by Django 5.0.3 on 2024-06-09 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messapp', '0009_userprofile_websocket_connected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='websocket_connected',
        ),
    ]
