# Generated by Django 5.0.3 on 2024-06-09 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messapp', '0011_userprofile_last_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_activity',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='online',
        ),
    ]
