# Generated by Django 5.0.3 on 2024-06-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messapp', '0012_remove_userprofile_last_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='private/messages/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='messagechannel',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='private/messages/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='messagegroup',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='private/messages/%Y/%m/%d/'),
        ),
    ]
