# Generated by Django 5.0.3 on 2024-06-09 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messapp', '0013_alter_message_attachment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageAttachment',
        ),
    ]
