# Generated by Django 5.0.3 on 2024-06-13 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messapp', '0018_userprofile_dark_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dark_theme',
            field=models.CharField(default='light', max_length=10),
        ),
    ]
